### ISSUE TITLE
Building with GN on Windows

### ISSUE THREAD

**Issue by vsimon** [vsimon/webrtcbuilds#22]
Fix any issues building with GN on Windows.

**Comment by DanielTBrown** [comment]
@vsimon Thank you for the improvements in the recent pull requests for webrtcbuilds. For the Microsoft Windows build, I propose to make the following changes:
- Use Microsoft Visual Studio 2015: eliminate the MSCSVER option, use the correct path for the Microsoft Visual Studio tools.
- Add the 'branch' option in addition to the 'revision' option. This is not related to Microsoft Windows, but is at least for me a useful feature, since I can build to match the feature set of a Google Chrome revision.

**Comment by vsimon** [comment]
@DanielTBrown thanks for the proposal update, the branch option will be a great addition.

**Comment by DanielTBrown** [comment]
Pull request #30 has the changes to use 'gn' under Microsoft Windows.

**Comment by vsimon** [comment]
Pull request has been merged. Closing.
