### ISSUE TITLE
Subclass link error

### ISSUE THREAD

**Issue by empirefox** [vsimon/webrtcbuilds#3]
Hi vsimon!
I got a lot link errors recently. I finally locate the problem after testing.
When extending subclass from some webrtc class ie rtc::Thread, g++ will say undefined reference to `typeinfo for rtc::Thread'.

Code:

``` C++
#include <iostream>
#include "webrtc/base/thread.h"

class GangCapturerThread: public rtc::Thread {
public:
    explicit GangCapturerThread() {
    }
    virtual ~GangCapturerThread() {
    }

    void Print() {
        std::cout << "ok" << std::endl;
    }
};

int main(int argc, char **argv) {
    GangCapturerThread thread;
    thread.Print();
}
```

Command:

```
g++ ./main.cc    `pkg-config --cflags --libs --define-variable=prefix=/home/savage/soft/webrtc/webrtc-linux64 libwebrtc_full` -o "ic-webrtc"
```

Error:

```
./main.o:(.rodata._ZTI18GangCapturerThread[_ZTI18GangCapturerThread]+0x10): undefined reference to `typeinfo for rtc::Thread'
collect2: error: ld returned 1 exit status
```

Another Test:

``` C++
#include <iostream>
#include "webrtc/base/thread.h"

int main(int argc, char **argv) {
    rtc::Thread* thread = rtc::Thread::Current();
    std::cout << thread->IsCurrent() << std::endl;
}
```

Everything's ok!
I've no idea what's wrong with the subclass.

**Comment by empirefox** [comment]
OH, It's my fault!
The "explicit", sorry.

**Comment by empirefox** [comment]
I think the no-rtti option solved the problem.But how can i mix -fno-rtti and -frtti in projects?

**Comment by vsimon** [comment]
Thanks for the updates! I'll look into mixtures of -fno-rtti (for webrtc) and -frtti (user apps).as well.

**Comment by vsimon** [comment]
You're right it seems webrtc builds with no-rtti by default. I read that having libraries linked with different RTTI flags is not a very good idea and may lead to a lot of surprises. I think user projects are likely to have it on by default so I pushed a patch to enable rtti on osx and linux here https://github.com/vsimon/webrtcbuilds-builder/commit/954e00430209f3c585eade96056343f7deee3285
If it turns out this is not the case, I can revisit this patch later, closing issue for the time being.

P.S. The latest builds for osx and linux starting from revision 9388 onward will be compiled with this patch.
