### ISSUE TITLE
demo file not found

### ISSUE THREAD

**Issue by jonahzheng** [vsimon/webrtcbuilds#43]
https://github.com/vsimon/webrtcbuilds/tree/master/talk/examples/peerconnection/client
https://github.com/vsimon/webrtcbuilds/tree/master/talk/examples/peerconnection/server

it can not find

**Comment by vsimon** [comment]
Thanks, you're right. This repo used to contain a mirror of the svn source of webrtc source but that has since been removed after webrtc itself moved to [git](https://chromium.googlesource.com/external/webrtc/). I've updated the [wiki page](https://github.com/vsimon/webrtcbuilds/wiki/Building-the-peerconnection-example) to point to the examples in the webrtc git repo.
